name: CI / CD Develop PR Closed

env:
  artifact_name: terraform-state-${{ github.event.pull_request.id }}
  bucket_name: pull-request-${{ github.event.pull_request.id }}

on:
  pull_request: 
    types: [closed]

jobs:
  destroy-deploy:
    name: Destroy Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init -backend-config="key=${{ env.bucket_name}}.tfstate" -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        working-directory: terraform
      - run: | 
          terraform apply -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="bucket_name=${{ env.bucket_name }}" -auto-approve -destroy
        working-directory: terraform