name: CI / CD Develop PR Closed
  
on:
  pull_request_target: 
    types: [closed]
    branches: 
      - develop

jobs:
  destroy-deploy:
    name: Destroy Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: terraform_state_${{ github.event.pull_request.user.name }}_${{ github.event.pull_request.created_at }}

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
        working-directory: terraform
      - run: | 
          terraform apply \ 
          -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \ 
          -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \ 
          -var="bucket_name=${{ github.event.pull_request.user.name }}_${{ github.event.pull_request.created_at }}" \
          -auto-approve \
          -destroy
        working-directory: terraform